import { LitElement, css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import * as L from 'leaflet';
import serviceCounties from './aiken-coop-counties.geojson';
import type { CountyStatus, OutageDetail } from './types.js';
@customElement('rv-outage-map')
export class RvOutageMap extends LitElement {
 @property({ attribute:false }) counties: CountyStatus[]=[]; @property({ attribute:false }) outages: OutageDetail[]=[]; private _map?:L.Map; private _layers?:L.LayerGroup; private _viewKey='';
 protected updated(){this._syncMap()} disconnectedCallback(){super.disconnectedCallback();this._map?.remove();this._map=undefined}
 private _key(n?:string){return(n??'').replace(/ county$/i,'').trim().toLowerCase()} private _fmt(v?:string){const d=v?new Date(v):undefined;return !d||Number.isNaN(d.getTime())?'-':d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
 private _syncMap(){const host=this.renderRoot.querySelector<HTMLElement>('#outage-leaflet-map');if(!host)return;if(!this._map){this._map=L.map(host,{zoomControl:true,scrollWheelZoom:false,preferCanvas:false});this._map.createPane('outage-boundaries').style.zIndex='450';this._map.createPane('outage-markers').style.zIndex='650';L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(this._map)}this._layers?.remove();this._layers=L.layerGroup().addTo(this._map);const counties=new Map(this.counties.map(c=>[this._key(c.name),c]));const boundaryRenderer=L.canvas({pane:'outage-boundaries',padding:0.5});const boundary=L.geoJSON(serviceCounties as GeoJSON.GeoJsonObject,{pane:'outage-boundaries',...({renderer:boundaryRenderer} as unknown as L.GeoJSONOptions),style:f=>{const c=counties.get(this._key(f?.properties?.NAME as string|undefined));const a=Number(c?.customersOutNow??0)>0;return{color:a?'#c8483a':'#35506b',weight:a?3:2,fill:true,fillColor:a?'#c8483a':'#6d8faa',fillOpacity:a?.62:.16}},onEachFeature:(f,layer)=>{const n=String(f.properties?.NAME??'County');layer.bindTooltip(n+': '+Number(counties.get(this._key(n))?.customersOutNow??0).toLocaleString()+' out',{sticky:true})}}).addTo(this._layers);boundary.bringToFront();const bounds=boundary.getBounds();for(const o of this.outages){const p=o.outagePoint;if(!Number.isFinite(Number(p?.lat))||!Number.isFinite(Number(p?.lng)))continue;const marker=L.circleMarker([Number(p!.lat),Number(p!.lng)],{pane:'outage-markers',radius:9,color:'#fff0df',weight:2,fillColor:'#c8483a',fillOpacity:1}).addTo(this._layers);marker.bindPopup('<b>'+(o.outageName??'ACTIVE OUTAGE')+'</b><br>'+Number(o.customersOutNow??0).toLocaleString()+' customers out<br>'+(o.crewAssigned?'Crew assigned':'Awaiting crew')+'<br>Started '+this._fmt(o.outageStartTime)+'<br>ETR '+(o.estimatedTimeOfRestoral??'TBD'));bounds.extend(marker.getLatLng())}const viewKey=JSON.stringify({counties:this.counties.map(c=>[c.name,c.customersOutNow]),outages:this.outages.map(o=>[o.outageName,o.outagePoint])});if(bounds.isValid()&&viewKey!==this._viewKey){this._map.fitBounds(bounds,{padding:[24,24],maxZoom:9});this._viewKey=viewKey;}requestAnimationFrame(()=>this._map?.invalidateSize())}
 render(){return html`<div id="outage-leaflet-map" aria-label="OpenStreetMap view of the Aiken Co-op service territory"></div>`}
 static styles=css`:host,#outage-leaflet-map{display:block;height:100%;min-height:420px;background:#d7dde2;font-family:system-ui,sans-serif}.leaflet-container{position:relative;overflow:hidden}.leaflet-pane{z-index:400}.leaflet-tile-pane{z-index:200}.leaflet-overlay-pane{z-index:400}.leaflet-marker-pane{z-index:600}.leaflet-tooltip-pane{z-index:650}.leaflet-popup-pane{z-index:700}.leaflet-map-pane svg{z-index:200;pointer-events:auto}.leaflet-pane,.leaflet-layer,.leaflet-zoom-animated,.leaflet-tile,.leaflet-marker-icon,.leaflet-tile-container,.leaflet-pane>svg,.leaflet-pane>canvas{position:absolute;left:0;top:0}.leaflet-pane>svg,.leaflet-pane>canvas{width:100%;height:100%}.leaflet-tile-container{pointer-events:none}.leaflet-overlay-pane svg{max-width:none!important;max-height:none!important}.leaflet-control{position:relative;z-index:800}.leaflet-top,.leaflet-bottom{position:absolute;z-index:1000}.leaflet-top{top:0}.leaflet-right{right:0}.leaflet-bottom{bottom:0}.leaflet-left{left:0}.leaflet-control-zoom{margin:10px;border:1px solid #777;border-radius:4px;overflow:hidden;box-shadow:0 1px 5px #777}.leaflet-control-zoom a{display:block;width:26px;height:26px;line-height:26px;text-align:center;background:#fff;color:#111;text-decoration:none;font-size:18px}.leaflet-control-zoom a+a{border-top:1px solid #ccc}.leaflet-control-attribution{margin:0;padding:2px 5px;background:rgba(255,255,255,.75);font-size:11px;color:#333}.leaflet-control-attribution a{color:#0078a8}.leaflet-popup{position:absolute;text-align:center;margin-bottom:20px}.leaflet-popup-content-wrapper{padding:1px;text-align:left;border-radius:5px;background:#20242b;color:#e7e3d8;box-shadow:0 3px 14px rgba(0,0,0,.4)}.leaflet-popup-content{margin:12px 14px;line-height:1.45}.leaflet-popup-tip{width:12px;height:12px;margin:-6px auto 0;background:#20242b;transform:rotate(45deg)}.leaflet-popup-close-button{position:absolute;right:4px;top:0;color:#d9a441;font-size:18px;text-decoration:none}`}